const ATOMIC_ORDER = [
    :Ca,
    :Na,
    :K,
    :Mg,
    :Sr,
    :Ba,
    :Al,
    :Fe,
    :Ti,
    :Mn,
    :Cr,
    :Si,
    :C,
    :H,
    :N,
    :S,
    :O,
    :P,
    :B,
    :F,
    :Cl,
    :Br,
    :I,
    :Zz,
]

const CEMENT_TO_MENDELEEV = [
    :C => OrderedDict(:Ca => 1, :O => 1),
    :M => OrderedDict(:Mg => 1, :O => 1),
    :S => OrderedDict(:Si => 1, :O => 2),
    :A => OrderedDict(:Al => 2, :O => 3),
    :F => OrderedDict(:Fe => 2, :O => 3),
    :K => OrderedDict(:K => 2, :O => 1),
    :N => OrderedDict(:Na => 2, :O => 1),
    :P => OrderedDict(:P => 2, :O => 5),
    :T => OrderedDict(:Ti => 1, :O => 2),
    :C̄ => OrderedDict(:C => 1, :O => 2),
    :S̄ => OrderedDict(:S => 1, :O => 3),
    :N̄ => OrderedDict(:N => 1, :O => 3),
    :H => OrderedDict(:H => 2, :O => 1),
]

const OXIDE_ORDER = collect(first.(CEMENT_TO_MENDELEEV))
