pages = [
    "Home" => "index.md",
    "Getting Started" => "quickstart.md",
    "Tutorial" => [
        "man/formula_manipulation.md",
        "man/species.md",
        "man/cement_species.md",
        "man/databases.md",
        "man/stoich_matrices.md",
        "man/reactions.md",
    ],
    "Examples" => ["examples/bogue_calculation.md",
                   "examples/example_stoich_matrix.md",
                   "examples/from_scratch.md"],
    "API" => Any[
    "Thermodynamical functions" => "api/thermo_functions.md",
    "Thermodynamical models" => "api/thermo_models.md",
    "Element order" => "api/element_order.md",
    "Parsing tools" => "api/parsing_tools.md",
    "Formulas" => "api/formulas.md",
    "Species" => "api/species.md",
    "Stoichiometric Matrix" => "api/stoich_matrices.md",
    "Reactions" => "api/reactions.md",
    ],
]
